// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApzWFh7KMHdi69e1Lpf9v787P_xVRx0Lg',
    appId: '1:239537472344:web:2fa3701d42c08c4fef5b2d',
    messagingSenderId: '239537472344',
    projectId: 'jvh-project',
    authDomain: 'jvh-project.firebaseapp.com',
    storageBucket: 'jvh-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp5eVWAMt6J0Vxra_v1aQUPlwCUlyvl6M',
    appId: '1:239537472344:android:ff8aeb01b2dd699eef5b2d',
    messagingSenderId: '239537472344',
    projectId: 'jvh-project',
    storageBucket: 'jvh-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBCsuUPb0ezbj0QvBowSwNyCS08Qs2Fs4',
    appId: '1:239537472344:ios:b660aee4664fcf28ef5b2d',
    messagingSenderId: '239537472344',
    projectId: 'jvh-project',
    storageBucket: 'jvh-project.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

}