# Uncomment this line to define a global platform for your project
# platform :ios, '15.0'

# CocoaPods analytics sends network requests to Google Analytics to track usage.
# Features like Cocoapods-Try are not working for app developers.
# For more information, see: https://github.com/CocoaPods/CocoaPods/issues/7641
#
# To disable analytics, uncomment the following line:
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_additional_ios_build_settings(target)
  use_frameworks! :linkage => :static
  target.build_configurations.each do |config|
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
      '$(inherited)',
      'FLUTTER_FRAMEWORK=1',
      'FB_SONARKIT_ENABLED=1',
      'SK_Ad_Network_ID=cstr6suwn9.skadnetwork'
    ]
  end
end

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
    end
  end
end
